export enum ApiCode {
	// Success
	OK = "OK",
	CREATED = "CREATED",
	NO_CONTENT = "NO_CONTENT",
	ACCEPTED = "ACCEPTED",

	// Client errors
	BAD_REQUEST = "BAD_REQUEST",
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	NOT_FOUND = "NOT_FOUND",
	CONFLICT = "CONFLICT",
	VALIDATION_ERROR = "VALIDATION_ERROR",
	TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

	// Server errors
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
}
