export enum DomainCode {
	EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
	INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN",

	OFFER_ALREADY_REVIEWED = "OFFER_ALREADY_REVIEWED",
	SELF_REVIEW_NOT_ALLOWED = "SELF_REVIEW_NOT_ALLOWED",
	USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
}
